"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { AppShell } from "@/components/AppShell";
import { getRealityScanDiagnostics, listRealityScanJobs, prepareRealityScanJob } from "@/lib/api";
import type { PhotogrammetryJob, RealityScanDiagnostics } from "@/lib/types";

export default function PhotogrammetryPage(){
 const {id}=useParams<{id:string}>(); const [diag,setDiag]=useState<RealityScanDiagnostics|null>(null); const [jobs,setJobs]=useState<PhotogrammetryJob[]>([]); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const load=()=>{getRealityScanDiagnostics().then(setDiag).catch(e=>setError(e.message));listRealityScanJobs(id).then(setJobs).catch(e=>setError(e.message));}; useEffect(load,[id]);
 async function prepare(){setBusy(true);setError("");try{await prepareRealityScanJob(id);load();}catch(e){setError(e instanceof Error?e.message:"Preparation failed");}finally{setBusy(false);}}
 return <AppShell><div className="mx-auto max-w-4xl"><div className="flex gap-4 text-sm text-slate-300"><Link href={`/projects/${id}/model-artifacts`}>Model Artifacts</Link><Link href={`/projects/${id}/report`}>Report</Link></div><div className="glass-panel mt-5 rounded-lg p-7"><p className="text-sm text-brand">External photogrammetry</p><h1 className="mt-2 text-3xl font-semibold text-white">RealityScan automation foundation</h1><p className="mt-3 text-sm text-slate-400">Structura prepares a local job and preserves a manual RealityScan bridge. Full headless automation is not enabled until this installation&apos;s CLI is verified.</p><div className="mt-5 rounded border border-white/10 p-4 text-sm"><p>Executable: {diag?.resolvedRealityScanExe ?? "Not found"}</p><p className="mt-2">Source: {diag?.source ?? "Checking"} · Headless: {String(diag?.supportsHeadless ?? "unknown")} · Command file: {String(diag?.supportsCommandFile ?? "unknown")}</p>{diag?.errors.map(x=><p key={x} className="mt-2 text-amber-100">{x}</p>)}</div><button disabled={busy} onClick={prepare} className="mt-5 rounded bg-brand px-4 py-2 text-sm font-semibold text-ink disabled:opacity-50">{busy?"Preparing...":"Prepare RealityScan job"}</button>{error&&<p className="mt-3 text-red-200">{error}</p>}</div><section className="glass-panel mt-6 rounded-lg p-6"><h2 className="font-semibold text-white">Manual RealityScan workflow</h2><ol className="mt-3 list-decimal space-y-2 pl-5 text-sm text-slate-300"><li>Open RealityScan and import the prepared job input folder.</li><li>Align images, build model, and build texture.</li><li>Export OBJ + MTL + textures as one ZIP.</li><li>Import the ZIP through Model Artifacts.</li></ol>{jobs.map(job=><div key={job.jobId} className="mt-4 rounded border border-white/10 p-4 text-sm text-slate-300"><p className="font-semibold">{job.status} · {job.imageCount ?? ""} images</p><p className="mt-2 break-all">Input: {job.inputImageFolder}</p><p className="break-all">Output: {job.outputFolder}</p><p className="mt-2 break-all text-xs">Draft command file: {job.commandFilePath}</p></div>)}</section></div></AppShell>;
}
